### PR TITLE
`[v7-doc-updates]`

### PR DESCRIPTION
**Pull request by harold**
- [x] New "Getting Started" doc
 - [x] Rewrite README
 - [x] Pass on Walkthrough
 - [x] Pass on Quick Reference

### CODE REVIEW

**Comment by harold** [comment]
Make sure to take updates from the `docs/` folder in this branch when resolving conflicts.

**Review by cnuernber — APPROVED** [review]
This looks really good.  I like the graphics here and there and I also like the new getting started doc.  Thank you very much for this work!!

**Comment by harold** [comment]
Excellent - you're welcome! Thank _you_ for all you've done on this project as well.

**Comment by harold** [comment]
I do think a next step, for some time down the road, would be to look at all of this again from a pure 'marketing' and 'shop window appeal' perspective - with the aim of producing an artifact like a pure public facing website/landing page.

Everything that's here is targeted at someone who is already convinced to use the library, selling people on using the library is a different job.

**Pull request merged**
