### PR TITLE
Some suggested changes

### PR DESCRIPTION
**Pull request by sogaiu**
Included are a few minor suggested changes.

In addition, there were a couple of things I wasn't sure of (and hence are not at this moment, a part of this PR):

1) The return value for `(dttype/->array-copy (nameage :age))` was:
```
#object["[J" 0x6d5c4fe4 "[J@6d5c4fe4"]
```
here and not:
```
[1, 2, 3, 4, 5]
```
as seen here: https://techascent.github.io/tech.ml.dataset/walkthrough.html

2) For:
```
(as-> (assoc stocks :years (dtype-dt/long-temporal-field :years (stocks :date))) stocks
        (ds/group-by stocks (juxt :symbol :years))
        (vals stocks)
        ;;stream is a sequence of datasets at this point.
        (map (fn [ds]
               {:symbol (first (ds :symbol))
                :years (first (ds :years))
                :avg-price (dfn/mean (ds :price))})
             stocks)
        (sort-by (juxt :symbol :years) stocks)
        (ds/->>dataset stocks)
        (ds/head stocks 10))
```
I got the following error:
```
Execution error (IllegalArgumentException) at tech.v3.protocols.dataset/eval12883$fn$G (dataset.clj:4).
No implementation of method: :columns of protocol: #'tech.v3.protocols.dataset/PColumnarDataset found for class: clojure.core$juxt$fn__5826
```
I tried it both via manual entry as well as copy-paste, but got the same result.

Not sure if I didn't set something up correctly or perhaps there's some other pilot error.

The commit I tested with was: 0c3769de1174041df665f2b1ccdba288d3d94058

Here is a log of my session: https://gist.github.com/sogaiu/316274b5556845cc55fab59fba052240

### CODE REVIEW

**Comment by cnuernber** [comment]
This is really helpful!  

The java array printing - that is a repl/cider difference.  My repl setup prints out arrays, I guess yours does not.

Everything you did looks right; I can't offhand see why the `as->` failed.  Trying again now.

**Comment by cnuernber** [comment]
That works again in my repl:
```clojure

user> (require '[tech.v3.dataset :as ds])
nil
user> (def stocks (ds/->dataset "https://github.com/techascent/tech.ml.dataset/raw/master/test/data/stocks.csv"
                                {:key-fn keyword}))
#'user/stocks
user> (require '[tech.v3.datatype.functional :as dfn])
nil
user> (require '[tech.v3.datatype.datetime :as dtype-dt])
nil

user> (as-> (assoc stocks :years (dtype-dt/long-temporal-field :years (stocks :date))) stocks
        (ds/group-by stocks (juxt :symbol :years))
        (vals stocks)
        ;;stream is a sequence of datasets at this point.
        (map (fn [ds]
               {:symbol (first (ds :symbol))
                :years (first (ds :years))
                :avg-price (dfn/mean (ds :price))})
             stocks)
        (sort-by (juxt :symbol :years) stocks)
        (ds/->>dataset stocks)
        (ds/head stocks 10))
_unnamed [10 3]:

| :symbol | :years |   :avg-price |
|---------|--------|--------------|
|    AAPL |   2000 |  21.74833333 |
|    AAPL |   2001 |  10.17583333 |
|    AAPL |   2002 |   9.40833333 |
|    AAPL |   2003 |   9.34750000 |
|    AAPL |   2004 |  18.72333333 |
|    AAPL |   2005 |  48.17166667 |
|    AAPL |   2006 |  72.04333333 |
|    AAPL |   2007 | 133.35333333 |
|    AAPL |   2008 | 138.48083333 |
|    AAPL |   2009 | 150.39333333 |
```

In your case it appears the failing is on the first group-by and that the (juxt :symbol :years) is being passed to the dataset group-by as the first argument and thus being interpreted as a dataset causing the protocol failure.

Could you past more of the stack trace?  This is an odd difference :-).

**Comment by sogaiu** [comment]
The log doesn't show this (sorry, I edited the log, my bad), but one thing that was different originally was that I evaluated expressions in the `tech.v3.dataset` namespace after doing:
```
(do
  (load-file "/home/user/src/tech.ml.dataset/src/tech/v3/dataset.clj") 
  (in-ns 'tech.v3.dataset))
```

When I do this first and go through the shorter code you posted (as well as the session log), I do get the exception.

Regarding more info from the stack trace, I don't see any other info.

**Comment by cnuernber** [comment]
Ah, then one reason could be that I use redefine sort-by in the dataset namespace but in my example I use both dataset sort-by and clojure.core/sort-by.  If you were in the dataset namespace it would always pick up dataset sort-by.

**Pull request merged**
