### PR TITLE
parse boolean string default to string, and update ->dataset docs

### PR DESCRIPTION
**Pull request by kimim**
- modification for issue #166 
- update docs for -> dataset. `:parser-fn` section is not well indented.

### CODE REVIEW

**Comment by cnuernber** [comment]
This change is equivalent to just never auto-detecting `:boolean`.   I do think that columns that contain only the strings `true` or `false` should parse to boolean values.

Currently the boolean parser is located here:  https://github.com/techascent/tech.ml.dataset/blob/master/src/tech/v3/dataset/io/column_parsers.clj#L59

How about removing some of those options in the cond statement?

**Comment by kimim** [comment]
If others are removed, then only `true` and `false` will be parsed. How about keep `:boolean`, but add `:bool`, which is more strict to parse only `false` and `true`, with case sensitive. That means the fall-back to string is also the same. But `:boolean` is still act as current implementation. While `:bool` is the default parser. `:boolean` should be specified in `:parser-fn`

**Comment by cnuernber** [comment]
That seems pretty reasonable.  I wouldn't make `:bool` so strict though, people type "True" "False" and "TRUE" "FALSE" and some database software will output things like that. 

That change is a bit harder as you will need to differentiate between the datatype `:boolean` and the parser directive `:bool`.

Perhaps the fixed type parsers can lookup their coercers in another map first or something like that.

I like the direction.

**Comment by kimim** [comment]
If `:bool` is not so strict, the fallback result is parsed as string, and the original string "True" or "FALSE" is changed to "true" and "false". Then some surprise happens...

**Comment by cnuernber** [comment]
Wow great point.  I agree then, let's go with only lower case.

**Comment by cnuernber** [comment]
This looks good and passes unit tests.  Are you finished with the work of this PR at this point?

**Comment by kimim** [comment]
Yes. I just fixed a document conflict. I'll defer the document modification in next PR. Now complete at the moment.

**Comment by cnuernber** [comment]
Hmm, and then I broke your PR by not checking in a file.  This is good as it is, the docs are completely regenerated every release.  Thanks for this work; I really appreciate it

**Pull request merged**
