### PR TITLE
Datasets as maps

### PR DESCRIPTION
**Pull request by cnuernber**
Large change -
After discussion on Zulip, @joinr was kind enough to offer patches that got us 90% of the way to having datasets derive from the appropriate map and funtional-map like interfaces.  

This carries this work into the master branch.  There were quite a few tests that had to be updated so I do expect some user regressions.

### CODE REVIEW

**Comment by joinr** [comment]
Is there anywhere we can see the build logs to determine what broke?  I think the preponderance of the culprits "should be" not using `(map column->data (vals the-dataset))` in lieu of the original column access `(map column->data the-dataset)`, or 3-arg invocations of datasets as IFns

**Comment by joinr** [comment]
Disregard, I got off my duff and dug into the CI links (haven't before).  sifting.

**Comment by cnuernber** [comment]
I made add-or-update-column work with constants and sequences - it now attemps to trim the sequence to the row length.  This failed when the dataset was empty so I handle that case specially now.

**Comment by joinr** [comment]
Looks like the CI build isn't picking up clojure CLI tool, unless I'm mistaken.

**Comment by joinr** [comment]
Ah there it goes, good.

**Comment by joinr** [comment]
I was going to say that we need to add a column check to tighten the bounds of what can be assoc'd, but it's already present in `add-or-update-column` which is what `assoc` is delegating to.  Trying to think of anything else that would allow leaky semantics and problem cases.  May be useful to wire up collection-check or something similar and ensure the implementation is accurate (that can be a lesser revision though, outside the scope of the PR).

**Comment by joinr** [comment]
I noticed the iterator implementation now returns map entries instead of cols.  That's more consistent, hopefully not painful for downstream users (they'll find out fairly quickly though with runtime type errors at least).

**Comment by cnuernber** [comment]
Yes, I was worried about some other production code that did some general map manipulation via iterating through the entries breaking.

**Comment by joinr** [comment]
For what it's worth, looks solid to my eyes.  Any changes would be additional features/implementing more protocols.  sweet

**Pull request merged**
