### PR TITLE
Spark integration

### PR DESCRIPTION
**Pull request by cnuernber**
Turned out that quick and dirty integration is damn simple.

### CODE REVIEW

**Comment by cnuernber** [comment]
@anthony-khong - relevate to your interests :-)

**Comment by anthony-khong** [comment]
Hi Chris, this looks cool! I think we can use the functions `spark-dataset->inplace-ds` and `ds->spark-dataset` in Geni to provide the conversion facilities from there too!

To check if I understood this, this is not zero copy right?

**Comment by cnuernber** [comment]
@anthony-khong - Correct, there is no way to do zerocopy.  Given a tech.ml.dataset, the best we can do is save it to disk or something and create an RDD from it.  This will, given arrow inplace, load the data bit by bit.  Else the entire file will be in memory.

Given a spark Dataset, the best we can do is convert it to an RDD and load each partition saving that partition out to an arrow or parquet file.

Honestly it doesn't seem to me like there is really that much to get from this now that dataset supports Parquet.  The best integration pathway is going to be to save a parquet file to disk and load it using dataset.

I think I will stop here and let this sit for a while unless we can figure out something we really want to do or try.

**Comment by anthony-khong** [comment]
All of that sounds very sensible. Thank you!

I want to start thinking about using Geni's syntax, but having the code run on TMD! Hopefully I can produce something to show you soon!

**Pull request merged**
