### PR TITLE
Tests pass with nil key eliding.

### LINKED ISSUE #363: Default to eliding missing values in JSON representation
Currently they can end up as null or NAN or a few different things so it would be ideal to just elide the key.  I currently believe that this behavior should be optional but defaulted on.

Concurrently ds/rows should have an option to elide missing keys - this should not be the default as there is a per-record perf cost inherent in this pathway but the option should be there and be clearly documented.

### PR DESCRIPTION
**Pull request by cnuernber**
Fixes #363

### CODE REVIEW

**Comment by cnuernber** [comment]
@harold - thoughts?

**Comment by harold** [comment]
> @harold - thoughts?

Seems cool. Did someone want this?

**Comment by cnuernber** [comment]
Yes - convo on slack

**Comment by harold** [comment]
I think that's sort of fine - we have hit similar in persist where you try to write a resource without a key (`dissoc`d), but the key persists because the old resource had a value there and with no key, no data gets written to that key. So, we `assoc` in `nil` and that overwrites it, and then downstream code that's `nil` punning correctly doesn't know the difference between absent key and key w/ `nil` value.

**Comment by cnuernber** [comment]
wow yeah that is another edge case - an upsert type operation will fail.  I guess you would really need a special marker value that was something like :tech/removed or the like to indicate to remove the value or a separate operation to indicate such.  Just upserting vanilla maps cannot ever remove a key.

**Pull request merged**
